---
- include: fedora.yml
  when: is_rhel7.rc != 0

- include: rhel7.yml
  when: is_rhel7.rc == 0

- name: Write etcd config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  notify:
        - restart etcd

- name: Enable etcd
  service: name=etcd enabled=yes

- name: Start etcd
  service: name=etcd state=started
  register: started_etcd

