---
- name: Determine if Atomic
  stat: path=/run/ostree-booted
  register: s
  changed_when: false

- name: Init the is_atomic fact
  set_fact:
    is_atomic: false

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: s.stat.exists

- name: Determine if RHEL7
  shell: "grep 'Red Hat Enterprise Linux.*release 7' /etc/redhat-release"
  register: is_rhel7
  failed_when: false
  changed_when: false

- include: rhel7_repos.yml
  when: is_rhel7.rc == 0 and not is_atomic

- name: Set IP address variables
  set_fact:
    master_ip_address: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"
    etcd_ip_address: "{{ hostvars[groups['etcd'][0]]['ansible_default_ipv4']['address'] }}"

- include: aws.yml
